# Generated by Django 4.2.5 on 2023-10-26 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_billing_profiles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='billing_profiles',
            new_name='billing_profile',
        ),
    ]
